### ISSUE TITLE
got plugin error on Android Studio 2.1

### ISSUE THREAD

**Issue by daquexian** [Qixingchen/DataBindingModelFormatter#1]
每次AS都提示Data Binding Formatter threw an uncaught PluginException，重启也没有效果，没有成功运行过T_T
版本是Android Studio 2.1

**Comment by Qixingchen** [comment]
可以贴出报错堆栈和相关的model代码么

**Comment by daquexian** [comment]
启用插件之后开启AS的时候就会报错0.0 所以没有报错堆栈和相关的model
这种插件错误似乎也没有log？0.0 我没有找到

**Comment by Qixingchen** [comment]
那我去尝试复现吧.
点击 AS 的 help 菜单中的 submit feedback 会弹出 android issue 页面,将那边的 Description 一栏的内容贴一下.

**Comment by daquexian** [comment]
Build: 2.1, AI-143.2790544, 20160422, 

1.7.0_111-b01x64 Oracle Corporation, Linux(amd64) v4.2.0-27-generic unknown (1920x1080) 

辛苦了，希望不会是只在我的电脑上会出现的问题。。

**Comment by Qixingchen** [comment]
Build: 2.1, AI-143.2790544, 20160422, 

1.8.0_101-b13x64 Oracle Corporation, Linux(amd64) v4.4.0-36-generic unknown (1280x1024, 1440x900) 

测试没有问题,也许与JDK版本有关 但是目前没有 JDK7 可用.
plugin error 的报错框记得是可以点击的,点击后会弹出 feedback 对话框.

**Comment by daquexian** [comment]
试了一下不能点击T_T
那我升级一下JDK试试，麻烦你啦～

**Comment by Qixingchen** [comment]
最近看了下 的确使用的是 Java 8 的开发环境

**Comment by daquexian** [comment]
谢啦~ 需要把 issue 关掉吗？

**Comment by Qixingchen** [comment]
我就关闭了 w
