### ISSUE TITLE
实现Observable不太好

### ISSUE THREAD

**Issue by liangjingkanji** [Qixingchen/DataBindingModelFormatter#2]
建议实现BaseObservable, 线程安全的

**Comment by Qixingchen** [comment]
感谢建议 后续会添加 synchronized 关键字,但目前没有实现 BaseObservable 的计划.

**Comment by liangjingkanji** [comment]
为什么啊?? BaseObservable有毛病么??? 我用过了仓库的所有DataBinding插件就你这个最实用

**Comment by Qixingchen** [comment]
BaseObservable 是继承的,如果 model 已经有其他继承了会导致生成失败.  
实际上 BaseObservable 就是实现了 Observable,添加 synchronized 关键字后两者在效果上就完全一致了.

https://android.googlesource.com/platform/frameworks/data-binding/+/c9a5d6f140f732ca0ff279a4b1ee315072e1c422/library/src/main/java/android/databinding/BaseObservable.java

**Comment by liangjingkanji** [comment]
的确. 对了DataBinding的inverse系列注解我实在不太懂, 你有文章推荐么? 我对DataBinding非常感兴趣

**Comment by Qixingchen** [comment]
双向绑定的话 看下  data binding 自带的几个 view 的适配器的代码可以很好的理解呢 比如给 textview 添加双向绑定的代码

https://android.googlesource.com/platform/frameworks/data-binding/+/android-7.0.0_r19/extensions/baseAdapters/src/main/java/android/databinding/adapters/TextViewBindingAdapter.java

更多适配器可以看 https://android.googlesource.com/platform/frameworks/data-binding/+/android-7.0.0_r19/extensions/baseAdapters/src/main/java/android/databinding/adapters

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/34461065-bcbf5f00-ee5b-11e7-98a8-1c86d8fb5f82.png)
我想知道的是这四个注解的用法

**Comment by Qixingchen** [comment]
这个我也没什么好的文章推荐 之前都是用 Google 搜了之后随便看的

**Comment by liangjingkanji** [comment]
executePendingBindings这个方法执行和不执行有什么区别啊, 我感觉我的RecyclerView都很正常
