### ISSUE TITLE
你好，现在版本没有支持Androidx

### ISSUE THREAD

**Issue by marklhp** [Qixingchen/DataBindingModelFormatter#4]
你好，现在版本没有支持Androidx

**Comment by Qixingchen** [comment]
正在提交更新  
目前没有完全对 AndroidX 进行测试,如遇问题请另开 Issue

**Comment by marklhp** [comment]
你好，咨询下你啊，开发Android studio  plugin插件使用的是什么IDE啊

**Comment by Qixingchen** [comment]
> 你好，咨询下你啊，开发Android studio plugin插件使用的是什么IDE啊

https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html
用 IDEA 开发
